# Generated by Django 5.2.3 on 2025-07-25 07:47

import budgidesk_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgidesk_app", "0002_remove_customuser_username_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", budgidesk_app.models.CustomUserManager()),
            ],
        ),
    ]
