# Generated by Django 5.2.3 on 2025-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgidesk_app", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalprofile",
            name="invoice_defaults",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                default="yes",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="late_notice",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="payment_methods",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="payment_terms",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="profession",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="sector",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
