# Generated by Django 5.1.11 on 2025-10-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budsi_database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="credit_note_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("purchase", "Purchase"),
                    ("credit_note", "Credit Note"),
                ],
                default="sale",
                max_length=12,
            ),
        ),
    ]
